- name: Configure backend server
  hosts: backend
  become: yes
  tasks:
    - name: Disable current Node.js module
      ansible.builtin.command: dnf module disable nodejs -y

    - name: Enable Node.js 20 module
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Install Node.js
      ansible.builtin.package:
        name: nodejs
        state: present