- name: Configure backend server
  hosts: backend
  become: yes
  tasks:
    - name: Disable current Node.js module
      ansible.builtin.command: dnf module disable nodejs -y

    - name: Enable Node.js 20 module
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Install Node.js
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: create expense user
      ansible.builtin.user:
        name: expense

    - name: create app Dir
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download backend code
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip

    - name: unzip backend code
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /app  
        remote_src: yes

    - name: install dependencies
      community.general.npm:
        src: /tmp/backend.zip
        path: /app
