- name: configure frontend server
  host: frontend
  become: yes
  taks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: enable and start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes    
