- name: Configure MySQL server
  hosts: MySql
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1
  tasks:
    - name: Install my libraries
      ansible.builtin.pip:
        name: PyMySQL
        executable: pip3.9
      loop:
      - cryptography
      - PyMySQL

    - name: Install MySQL server
      ansible.builtin.package:
        name: mysql-server
        state: present
    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
    - name: Get MySQL version with non-default credentials
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_host: mysql.mjs15.site
      register: mysql_info
      ignore_errors: true

    - name: Print the output
      ansible.builtin.debug:
        msg: "MySQL info: {{ mysql_info }}"
    
    - name: Setup root password
      ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }} "
      when: mysql_info.failed is true


        
