- name: Configure MySQL server
  hosts: MySql
  become: yes
  tasks:
    - name: Install MySQL server
      ansible.builtin.package:
        name: mysql-server
        state: present
    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
        
