---
- name: variables
  hosts: local
  connection: local
  gather_facts: false
  vars:
    course_name: "Course in DevOps with Ansible"

  tasks:
    - name: print the course name
      msg: "{{ course_name }}"