- name: Variables
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
  - course.yaml
  tasks:
  - name: print the variable
    ansible.builtin.debug:
    msg: "Hello from {{ GREET }}"
